export interface pokemon {
    id: number,
    name: PokemonName,
    height: number,
    weight: number,
    type: Array<Type>,
    hp: { base: number, max: number },
    cp: {max: CP}
    moves: {quick: Array<Quick_Move>, main: Array<Main_Move>}
    evolution: { base: PokemonName, evolve: number }
}

export interface Quickmove {
    name: Quick_Move,
    type: Type,
    dps: number
}

export interface Mainmove {
    name: Main_Move,
    type: Type,
    dps: number
}

export interface CP {
    15: number,
    20: number,
    30: number,
    40: number
}


// ENUMS


export enum Type {
    normal = "normal",
    fighting = "fighting",
    flying = "flying",
    poison = "poison",
    ground = "ground",
    rock = "rock",
    bug = "bug",
    ghost = "ghost",
    steal = "steal",
    fire = "fire",
    water = "water",
    grass = "grass",
    electric = "electric",
    psychic = 'psychic',
    ice = "ice",
    dragon = "dragon",
    dark = "dark",
    fairy = "fairy"
}

export enum Quick_Move {
    vineWhip = "Vine Whip",
    tackle = "Tackle",
    struggle = "Struggle",
    steelWing = "Steel Wing",
    dragonTail = "Dragon Tail",
    ironTail = "Iron Tail",
    rockThrow = "Rock Throw",
    fireFang = "Fire Fang",
    counter = "Counter",
    waterfall = "Waterfall",
    smackDown = "SmackDown",
    charm = "Charm",
    razorLeaf = "Razor Leaf",
    shadowClaw = "Shadow Claw",
    mudSlap = "Mud Slap",
    fireSpin = "Fire Spin",
    incinerate = "Incinerate",
    poisonJab = "Posion Jab",
    confusion = "Confusion",
    gust = "Gust",
    bite = "Bite",
    bragonBreath = "Dragon Breath",
    scratch = "Scratch",
    pound = "Pound",
    airSlash = "Air Slash",
    rockSmash = "RockSmash",
    metalClaw = "Metal Claw",
    acid = "Acid",
    frostBreath = "Frost Breath",
    feintAttack = "Feint Attack",
    zenHeadbutt = "Zen Headbutt",
    extrasensory = "Extrasensory",
    snarl = "Snarl",
    bugBite = "Bug Bite",
    suckerPunch = "Sucker Punch",
    lowKick = "Low Kick",
    karateChop = "Karate Chop",
    ember = "Ember",
    wingAttack = "Wing Attack",
    peck = "Peck",
    lick = "Lick",
    iceShard = "Ice Shard",
    quickAttack = "Quick Attack",
    cut = "Cut",
    bulletPunch = "Bullet Punch",
    waterGun = "Water Gun",
    bubble = "Bubble",
    struggleBug = "Struggle Bug",
    hiddenPower = "Hidden Power",
    thunderFang = "Thunder Fang",
    infestation = "Infestation",
    voltSwitch = "Volt Switch",
    thunderShock = "Thunder Shock",
    mudShot = "Mud Shot",
    psychoCut = "Psycho Cut",
    poisonSting = "Poison Sting",
    hex = "Hex",
    iceFang = "Ice Fang",
    furyCutter = "Fury Cutter",
    chargeBeam = "Charge Beam"
}

export enum Main_Move {
    seedBomb = "Seed Bomb",
    sludgeBomb = "Sludge Bomb",
    powerWhip = "Power Whip",
    originPulse = "Origin Pulse",
    braveBird = "Brave Bird",
    precipiceBlades = "Pecipice Blades",
    technoBlast = "Techno Blast",
    aeroBlast = "Aero Blast",
    leafStorm = "Leaf Storm",
    megaHorn = "Mega Horn",
    return = "Return",
    auraSphere = "Aura Sphere",
    flyingPress = "Flying Press",
    hydroCannon = "Hydro Cannon",
    sacredSowrd = "Sacred Sword",
    payback = "Packback",
    crabHammer = "crabHammer",
    futureSight = "FutureSight",
    fly = "Fly",
    stoneEdge = "Stone Edge",
    closeCombat = "Close Combat",
    gigaImpact = "Giga Impact",
    petalBlizzard = "Petal Blizzard",
    blizzard = "Blizzard",
    gunkShot = "Gunk Shot",
    skullBash = "Skull Bash",
    thunder = "Thunder",
    dracoMeteor = "Draco Meteor",
    doomDesire = "Doom Desire",
    hurricane = "Hurricane",
    focusBlast = "FocusBlast",
    skyAttack = "Sky Attack",
    overheat = "Over Heat",
    hyperBeam = "Hyper Beam",
    hydroPump = "Hydro Pump",
    earthquake = "Earthquake",
    frenzyPlant = "Frenzy Plant",
    meteorMash = "Meteor Mash",
    surf = "Surf",
    zapCannon = "Zap Cannon",
    weatherBall = "Weather Ball",
    blazeKick = "Blaze Kick",
    solarBeam = "Solar Beam",
    foulPlay = "Foul Play",
    powerWip = "Power Wip",
    wildCharge = "wild Charge",
    grassKnot = "Grass Knot",
    sludgeWave = "Sludge Wave",
    shadowBall = "Shadow Ball",
    moonBlast = "moonBlast",
    fireBlast = "Fire Blast",
    dynamicPunch = "Dynamic Punch",
    avalanche = "Avalanche",
    heavySlam = "Heavy Slam",
    blastBurn = "Blast Burn",
    dragonClaw = "Dragon Claw",
    leafeBlade = "Leaf Blade",
    shadowBone = "Shadow Bone",
    drillPeck = "Drill Peck",
    dazzlingGleam = "Dazzling Gleam",
    powerGem = "Power Gem",
    darkPulse = "Dark Pulse",
    icePunch = "Ice Punch",
    thunderPunch = "Thunder punch",
    dragonPulse = "Dargon Pulse",
    firePunch = "Fire Punch",
    shadowPunch = "Shadow Punch",
    aerialAce = "Aerial Ace",
    waterPulse = "Water Pulse",
    swift = "Swift",
    twister = "Twister",

}

export enum PokemonName {
    bulbasaur = "Bulbasaur",
    ivysaur = "Ivysaur",
    venusaur = "Venusaur",
    charmander = "Charmander",
    charmeleon = "Charmeleon",
    charizard = "Charizard",
    squirtle = "Squirtle",
    wartortle = "Wartortle",
    blastoise = "Blastoise",
    catapie = "Catapie",
    metapod = "Metapod",
    butterfree = "Butterfree",
    weedle = "Weedle",
    kakuna = "Kakuna",
    beedrill = "Beedrill",
    pidgey = "Pidgey",
    pidgeotto = "Pidgeotto",
    rattata = "Rattata",
    raticate = "Raticate",
    spearow = "Spearow",
    fearow = "Fearow",
    ekans = "Ekans",
    arbock = "Arbock",
    pikachu = "Pikachu",
    raichu = "Raichu",
    sandshrew = "Sandshrew",
    sandslash = "Sandslash",
    nidoran = "Nidoran",
    nidorina = "Nidorina",
    nidoqueen = "Nidoqueen",
    nidoking = "Nidoking",
    cleffa = "Cleffa",
    clefairy = "Clefairy",
    clefable = "cleable",
    vulpix = "Vulpix",
    ninetails = "Ninetails",
    jigglypuff = "Jigglypuff",
    wigglypuff = "wigglypuff",
    zubat = "Zubat",
    golbat = "Golbat",
    croBat = "Crobat",
    oddish = "Oddish",
    gloom = "Gloom",
    vileplume = "Vileplume",
    paras = "Paras",
    parasect = "parasect",
    venonat = "Venonat",
    venomoth = "Venomoth",
    diglett = "Diglett",
    dugtrio = "Dugtrio",
    meowth = "meowth",
    persion = "Persion",
    psyduck = "Psyduck",
    golduck = "Golduck",
    mankey = "Mankey",
    primeape = "Primeape",
    growlithe = "Growlithe",
    arcanine = "Arcanine",
}
